import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import CustomAlert from "@/components/CustomAlert";
import { notFound } from "next/navigation";
import NextIntlProvider from "./NextIntlProvider";

const inter = Inter({ subsets: ["latin"] });

const locales = ["en", "hi"];

export const metadata: Metadata = {
  title: "Employee Details",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  let messages;
  try {
    messages = (await import(`../../../messages/${locale}.json`))
      .default;
  } catch (error) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlProvider
          locale={locale}
          messages={messages}
          timeZone="Asia/Kolkata"
          now={new Date()}
        >
          {children}
          <CustomAlert />
        </NextIntlProvider>
      </body>
    </html>
  );
}
